<table class="table">
    <tr>
        <th>Book</th>
        <th>Compatibility</th>
        <th>Book Date</th>
        <th>Female AVG age</th>
        <th>Male AVG age</th>
    </tr>
    <?php foreach ($this->books as $book) : ?>
        <tr>
            <td><?= $this->escapeHtml($book->getName()) ?></td>
            <td><?= $book->getCompatibility() ?>%</td>
            <td><?= $book->getBookDate() ?></td>
            <td><?= number_format($book->getFemaleAVG(), 2, '.', ''); ?></td>
            <td><?= number_format($book->getMaleAVG(), 2, '.', ''); ?></td>
        </tr>
    <?php endforeach; ?>
</table>